# Generated by Django 6.0.6 on 2026-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('issued_by', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=220)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('year_range', models.CharField(max_length=80)),
                ('extra_info', models.CharField(blank=True, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vivek Ray', max_length=120)),
                ('role', models.CharField(default='Aspiring Software Developer', max_length=120)),
                ('tagline', models.CharField(default='Building Modern Web Applications with Django & JavaScript', max_length=240)),
                ('location', models.CharField(default='Madhubani, Bihar, India', max_length=120)),
                ('email', models.EmailField(default='vivekray7970@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 7970936214', max_length=40)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/vivek-rai-1b06893C')),
                ('github_url', models.URLField(default='https://github.com/vivekrai7970-max')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('technologies', models.CharField(max_length=220)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('case_study_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('proficiency', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
