# Generated by Django 6.1 on 2026-08-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='view_contac_email_70b807_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='view_contac_email_s_063dfc_idx',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
